#!/bin/bash -e
mkdir -p dist
if [ "$BRANCH" = "website2" ] || [ "$CIRCLE_BRANCH" = "website2" ]
then
  (cd website2 && yarn && yarn build)
  rsync -avz website2/.vuepress/dist/ dist/
else
  rsync -avz website/ dist/
fi
rsync -avz eventpop dist/
